# Generated by Django 4.2.5 on 2023-09-26 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_presence_etat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presence',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='presence',
            name='prenom',
        ),
    ]
