# Generated by Django 4.2.5 on 2023-09-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_presence_nom_remove_presence_prenom'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='Prenom',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presence',
            name='nom',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
