# Generated by Django 4.2.5 on 2023-09-26 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_presence_prenom_presence_nom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presence',
            old_name='Prenom',
            new_name='prenom',
        ),
    ]
